import { LivesWith, BloodType, RhFactor, BirthsType, SchoolLevel } from './enums.model';

export class ClinicalHistory {
  height:number;
  weight:number;
  livesWith: LivesWith;
  schoolLevel: SchoolLevel;
  profession:string;
  bloodType:BloodType;
  rhFactor:RhFactor;
  inMedicalTreatment:boolean;
  medicalTreatmentDetail:string;
  allergic:boolean;
  allergyDetail:string;
  hemorrhage:boolean;
  hemorrhageDetail:string;
  seizures:boolean;
  seizuresDetail:string;
  smoker:boolean;
  smokerDetail:string;
  practiceSports:boolean;
  sportsDetail:string;
  rheumatoidArthritis:boolean;
  kidneyProblems:boolean;
  asthma:boolean;
  arterialHypertension:boolean;
  mellitusDiabetes1:boolean;
  mellitusDiabetes2:boolean;
  hIV:boolean;
  anemia:boolean;
  hepatitis:boolean;
  heartProblems:boolean;
  tuberculosis:boolean;
  cancer:boolean;
  headache:boolean;
  epilepsy:boolean;
  cOPD:boolean;
  surgeries:boolean;
  hypothyroidism:boolean;
  otherDiseases:string;
  pacemaker:boolean;
  prosthesis:boolean;
  prosthesisDetail:string;
  hasBeenPregnant:boolean;
  pregnancies:number;
  birthsType:BirthsType;
  childrenBorn:number;
  familiarDiabetes:boolean;
  familiarDiabetesDetail:string;
  familiarArterialHypertension:boolean;
  familiarArterialHypertensionDetail:string;
  familiarHeartProblems:boolean;
  familiarHeartProblemsDetail:string;
  familiarCancer:boolean;
  familiarCancerDetail:string;
  otherFamilyDiseases:string;
}
